### ISSUE TITLE
Why in-distribution classification results are so bad? 

### ISSUE THREAD

**Issue by algoteam5** [Jingkang50/ICCV21_SCOOD#4]
I tested your model. The model could detect ood images quite well, but when it comes to classifying in-distribution classes. The model produced very bad results with wrong class label. So why in-distribution classification results are so bad?

**Comment by Jingkang50** [comment]
Thank you for your question. 
In the paper (Section 5.1 - Effectiveness of Unlabeled Data part) we found that ID accuracy drops on all OE-based methods, which introduce unlabeled data during training. 
One intuitive explanation is that when the OE loss forces the separation between training ID and training OOD, the discrepancy between ID classes become blurred, which leads to bad ID classification compared to output-based methods like MSP/ODIN. 
The phenomenon get even worse when training OOD is noisy (i.e. ID samples in unlabeled set still follow OE loss).
However, our method UDG can usually relieve the ID classification drawbacks compared to OE methods (due to ID filtering and the extra unsupervised learning task), but still cannot reach the performance of MSP/ODIN, which might intrigues further works.
